# Generated by Django 2.1 on 2018-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgmtserver',
            name='MgmtFingerPrintAPI',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.AlterField(
            model_name='mgmtserver',
            name='MGMTR80IsAlive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mgmtserver',
            name='MgmtR80VersionsSupported',
            field=models.CharField(choices=[('R80', 'R80'), ('R80.10', 'R80.10')], default='R80.10', max_length=10),
        ),
    ]
