# Generated by Django 2.1 on 2018-09-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0002_auto_20180828_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleGeneralDeploy',
            fields=[
                ('AnsibleResourceGroup', models.CharField(max_length=20)),
                ('AnsibleTMLocation', models.CharField(max_length=10)),
                ('AnsibleCredentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='APIR80.R80Users')),
            ],
        ),
    ]
