# Generated by Django 2.1.1 on 2018-10-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0005_auto_20181013_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgmtserverobjects',
            name='MGMTServerObjectsFilePath',
        ),
        migrations.RemoveField(
            model_name='mgmtserverobjects',
            name='MGMTServerPortsFilePath',
        ),
        migrations.AddField(
            model_name='mgmtserverobjects',
            name='MGMTServerFilePath',
            field=models.CharField(default='/home/carlos/django-chkp/APIR80/tmp/', max_length=250),
        ),
        migrations.AddField(
            model_name='mgmtserverobjects',
            name='MGMTServerFileType',
            field=models.CharField(choices=[('Ports', 'Ports'), ('Networks', 'Networks')], default='Ports', max_length=50),
        ),
    ]
