# Generated by Django 2.1.1 on 2018-10-13 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0007_auto_20181013_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGMTServerObjectsNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGMTServerFilePathNetObjects', models.CharField(default='/home/carlos/django-chkp/APIR80/tmp/chkpobjects.txt', max_length=250)),
                ('MGMTServerObjectsNetworksID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIR80.MGMTServer')),
            ],
        ),
    ]
