# Generated by Django 2.1.1 on 2018-10-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0010_auto_20181014_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGMTServerObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MGMTServerFilePathTCPPorts', models.CharField(default='/home/carlos/django-chkp/APIR80/tmp/chkpports.txt', max_length=250)),
                ('MGMTServerFilePathNetObjects', models.CharField(default='/home/carlos/django-chkp/APIR80/tmp/chkpobjects.txt', max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='mgmtserverobjectsnetworks',
            name='MGMTServerObjectsNetworksID',
        ),
        migrations.RemoveField(
            model_name='mgmtserverobjectstcpports',
            name='MGMTServerObjectsID',
        ),
        migrations.AlterField(
            model_name='mgmtserver',
            name='LastPublishSession',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='MGMTServerObjectsNetworks',
        ),
        migrations.DeleteModel(
            name='MGMTServerObjectsTCPPorts',
        ),
        migrations.AddField(
            model_name='mgmtserverobjects',
            name='MGMTServerObjectsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APIR80.MGMTServer'),
        ),
    ]
