# Generated by Django 2.1.5 on 2019-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIR80', '0013_mgmtserverobjects_mgmtserverfilepathnetworksobjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgmtserverobjects',
            name='MGMTServerFilePathNetObjects',
            field=models.CharField(default='/home/carlos/gitdjango/django-chkp/APIR80/tmp/chkpobjects.txt', max_length=250),
        ),
        migrations.AlterField(
            model_name='mgmtserverobjects',
            name='MGMTServerFilePathNetworksObjects',
            field=models.CharField(default='/home/carlos/gitdjango/django-chkp/APIR80/tmp/chkpobjectsnetworks.txt', max_length=250),
        ),
        migrations.AlterField(
            model_name='mgmtserverobjects',
            name='MGMTServerFilePathTCPPorts',
            field=models.CharField(default='/home/carlos/gitdjango/django-chkp/APIR80/tmp/chkpports.txt', max_length=250),
        ),
        migrations.AlterField(
            model_name='mgmtserverobjects',
            name='MGMTServerFilePathUDPPorts',
            field=models.CharField(default='/home/carlos/gitdjango/django-chkp/APIR80/tmp/chkpudpports.txt', max_length=250),
        ),
    ]
